---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knls-config
data:
  knls.yaml: |
{{- with .Values.cluster_url }}
    cluster_url: {{ . |quote }}
{{- end }}

{{- with .Values.extra_conf }}
{{ . |indent 4 }}
{{- end }}

    proxy: !nftables {}
{{ if .Values.dns }}
    dns: !{{.Values.dns}}
      cluster_domain: {{ .Values.cluster_domain |quote }}
      on_create:
      - !nft_chain
        table: knls
        chain: dns
        rules: |-
          type nat hook prerouting priority -101; policy accept;
{{-   range .Values.service_ips }}
          ip daddr {{.}} udp dport 53 redirect;
{{-   end }}
{{- end }}

{{ if .Values.connectivity}}
    connectivity: !{{.Values.connectivity}}
{{- if eq .Values.connectivity "wireguard" }}{{ with .Values.wireguard}}
      ifname: {{.ifname |quote}}
      key_path: "/var/lib/knls/wireguard/{{.key}}"
      on_create:
      - !nft_chain
        table: knls
        chain: wireguard
        rules: |-
          type nat hook postrouting priority 999; policy accept;
          fib saddr type local oif {{ .ifname |quote }} masquerade
{{- end }}{{ end }}
{{- end }}

  unbound.conf: |
    server:
{{ .Values.unbound.listen |indent 6 }}

      chroot: ""
      use-syslog: no
      verbosity: 1
      trust-anchor-file: "/usr/share/dnssec-root/trusted-key.key"
      qname-minimisation: yes
      do-not-query-localhost: no

      domain-insecure: {{ .Values.cluster_domain |quote }}
      local-zone: {{ .Values.cluster_domain |quote }} nodefault
    {{- range (keys .Values.extra_zones) }}
      domain-insecure: {{ . |quote }}
      local-zone: {{ . |quote }} nodefault
    {{- end}}

{{ .Values.unbound.server_extra |indent 6 }}

    stub-zone:
      name: {{ .Values.cluster_domain |quote }}
      stub-addr: 127.0.0.1@1053
      stub-no-cache: yes

    {{- range (keys .Values.extra_zones) }}
    auth-zone:
      name: {{ . |quote }}
      zonefile: /zones/{{.}}
      for-downstream: no
    {{- end}}

{{ .Values.unbound.extra_conf |indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knls-zones
data:
{{ .Values.extra_zones |toYaml |indent 2 }}

