---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knls
  labels:
    app: knls
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knls
  labels:
    app: knls
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knls
  labels:
    app: knls
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knls
subjects:
- kind: ServiceAccount
  name: knls
  namespace: {{ .Release.Namespace }}

