---
apiVersion: v1
kind: Service
metadata:
  name: knls
  labels:
    app: knls
spec:
  type: ClusterIP
{{- if .Values.service_ips }}
  clusterIP: {{ index .Values.service_ips 0 |quote }}
  clusterIPs: {{ .Values.service_ips |toJson }}
{{- end }}
  internalTrafficPolicy: Local
  selector:
    app: knls
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
    - name: dns-tls
      port: 853
    - name: dns-quic
      port: 853
      protocol: UDP
